setGeneric("wtFiles", function(obj) standardGeneric("wtFiles"))
setGeneric("mutFiles", function(obj) standardGeneric("mutFiles"))
setGeneric("refFasta", function(obj) standardGeneric("refFasta"))
setGeneric("gtf", function(obj) standardGeneric("gtf"))
setGeneric("outputFolder", function(obj) standardGeneric("outputFolder"))
setGeneric("includeScaffolds", function(obj) standardGeneric("includeScaffolds"))
setGeneric("minDepth", function(obj) standardGeneric("minDepth"))
setGeneric("homozygoteCutoff", function(obj) standardGeneric("homozygoteCutoff"))
setGeneric("minBaseQuality", function(obj) standardGeneric("minBaseQuality"))
setGeneric("minMapQuality", function(obj) standardGeneric("minMapQuality"))
setGeneric("fileAggregation", function(obj) standardGeneric("fileAggregation"))
setGeneric("distancePower", function(obj) standardGeneric("distancePower"))
setGeneric("peakIntervalWidth", function(obj) standardGeneric("peakIntervalWidth"))
setGeneric("loessOptResolution", function(obj) standardGeneric("loessOptResolution"))
setGeneric("loessOptCutFactor", function(obj) standardGeneric("loessOptCutFactor"))

setGeneric("maxPileupDepth", function(obj) standardGeneric("maxPileupDepth"))
setGeneric("candidateMinDepth", function(obj) standardGeneric("candidateMinDepth"))
setGeneric("candidateMinAltDepth", function(obj) standardGeneric("candidateMinAltDepth"))
setGeneric("candidateMinAltFreq", function(obj) standardGeneric("candidateMinAltFreq"))
setGeneric("candidateMaxWtAltFreq", function(obj) standardGeneric("candidateMaxWtAltFreq"))
setGeneric("candidateMinDeltaAF", function(obj) standardGeneric("candidateMinDeltaAF"))
setGeneric("candidatePoolMode", function(obj) standardGeneric("candidatePoolMode"))
setGeneric("candidateChunkSize", function(obj) standardGeneric("candidateChunkSize"))
setGeneric("peakCutoffSd", function(obj) standardGeneric("peakCutoffSd"))
setGeneric("peakCutoffMethod", function(obj) standardGeneric("peakCutoffMethod"))
setGeneric("peakIntervalMethod", function(obj) standardGeneric("peakIntervalMethod"))
setGeneric("peakResampleIterations", function(obj) standardGeneric("peakResampleIterations"))
setGeneric("randomSeed", function(obj) standardGeneric("randomSeed"))
setGeneric("pairedEnd", function(obj) standardGeneric("pairedEnd"))
setGeneric("ignoreStrand", function(obj) standardGeneric("ignoreStrand"))
setGeneric("expressionPseudocount", function(obj) standardGeneric("expressionPseudocount"))
setGeneric("exportAiccPlots", function(obj) standardGeneric("exportAiccPlots"))

setGeneric("wtFiles<-", function(obj, value) standardGeneric("wtFiles<-"))
setGeneric("mutFiles<-", function(obj, value) standardGeneric("mutFiles<-"))
setGeneric("refFasta<-", function(obj, value) standardGeneric("refFasta<-"))
setGeneric("gtf<-", function(obj, value) standardGeneric("gtf<-"))
setGeneric("outputFolder<-", function(obj, value) standardGeneric("outputFolder<-"))
setGeneric("includeScaffolds<-", function(obj, value) standardGeneric("includeScaffolds<-"))
setGeneric("minDepth<-", function(obj, value) standardGeneric("minDepth<-"))
setGeneric("homozygoteCutoff<-", function(obj, value) standardGeneric("homozygoteCutoff<-"))
setGeneric("minBaseQuality<-", function(obj, value) standardGeneric("minBaseQuality<-"))
setGeneric("minMapQuality<-", function(obj, value) standardGeneric("minMapQuality<-"))
setGeneric("fileAggregation<-", function(obj, value) standardGeneric("fileAggregation<-"))
setGeneric("distancePower<-", function(obj, value) standardGeneric("distancePower<-"))
setGeneric("peakIntervalWidth<-", function(obj, value) standardGeneric("peakIntervalWidth<-"))
setGeneric("loessOptResolution<-", function(obj, value) standardGeneric("loessOptResolution<-"))
setGeneric("loessOptCutFactor<-", function(obj, value) standardGeneric("loessOptCutFactor<-"))
setGeneric("maxPileupDepth<-", function(obj, value) standardGeneric("maxPileupDepth<-"))
setGeneric("candidateMinDepth<-", function(obj, value) standardGeneric("candidateMinDepth<-"))
setGeneric("candidateMinAltDepth<-", function(obj, value) standardGeneric("candidateMinAltDepth<-"))
setGeneric("candidateMinAltFreq<-", function(obj, value) standardGeneric("candidateMinAltFreq<-"))
setGeneric("candidateMaxWtAltFreq<-", function(obj, value) standardGeneric("candidateMaxWtAltFreq<-"))
setGeneric("candidateMinDeltaAF<-", function(obj, value) standardGeneric("candidateMinDeltaAF<-"))
setGeneric("candidatePoolMode<-", function(obj, value) standardGeneric("candidatePoolMode<-"))
setGeneric("candidateChunkSize<-", function(obj, value) standardGeneric("candidateChunkSize<-"))
setGeneric("peakCutoffSd<-", function(obj, value) standardGeneric("peakCutoffSd<-"))
setGeneric("peakCutoffMethod<-", function(obj, value) standardGeneric("peakCutoffMethod<-"))
setGeneric("peakIntervalMethod<-", function(obj, value) standardGeneric("peakIntervalMethod<-"))
setGeneric("peakResampleIterations<-", function(obj, value) standardGeneric("peakResampleIterations<-"))
setGeneric("randomSeed<-", function(obj, value) standardGeneric("randomSeed<-"))
setGeneric("pairedEnd<-", function(obj, value) standardGeneric("pairedEnd<-"))
setGeneric("ignoreStrand<-", function(obj, value) standardGeneric("ignoreStrand<-"))
setGeneric("expressionPseudocount<-", function(obj, value) standardGeneric("expressionPseudocount<-"))
setGeneric("exportAiccPlots<-", function(obj, value) standardGeneric("exportAiccPlots<-"))

setGeneric("param", function(obj) standardGeneric("param"))
setGeneric("param<-", function(obj, value) standardGeneric("param<-"))
setGeneric("snpDistance", function(obj) standardGeneric("snpDistance"))
setGeneric("peaks", function(obj) standardGeneric("peaks"))
setGeneric("candidates", function(obj) standardGeneric("candidates"))
